import Head from "next/head";
import Link from "next/link";
import Button from "@/components/Button";
import { GiZeusSword } from "react-icons/gi";
import Image from "next/image";
import AnimatedText from "@/components/AnimatedText";
import { mont_bold, mont_thin } from "@/styles/fonts";

export default function Home() {
  return (
    <>
      <Head>
        <title>Zeus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/zeus.avif" />
      </Head>
      <main>
        <div
          style={{ fontFamily: mont_thin.style.fontFamily }}
          className="uppercase text-gray-600 m-2 mb-5 text-4xl"
        >
          <AnimatedText text="Ask the gods!" />
        </div>
        <div className="grid grid-cols-2 place-items-center gap-4">
          <Link href="/models/zeus">
            <Button
              title={"Zeus"}
              model="code-cushman-001"
              img={<Image src="/zeus.png" width={66} height={66} />}
              desc="Zeus is the king of the gods and the supreme deity worshiped by the ancient Greeks as the ruler of the gods on Mount Olympus. He
                    can assist you in generating and explaining code realted problems."
            />
          </Link>
          <Link href="/models/prometheus">
            <Button
              title={"Prometheus"}
              model="text-davinci-003"
              img={<Image src="/prometheus.png" width={66} height={66} />}
              desc="Prometheus is regarded as a champion of mankind and a symbol of creative
                    intelligence and defiance against the arbitrary power of the gods. He
                    can assist you in generating literature novelties."
            />
          </Link>
          <Link href="/models/muses">
            <Button
              title={"Muses"}
              model="text-ada-001"
              img={<Image src="/demeter.png" width={66} height={66} />}
              desc="Muses were the nine goddesses of the arts and sciences, including poetry, music, dance, and history. They were considered the source of inspiration for all creative artists. She can help with note summaries and keyword extraction from long passages."
            />
          </Link>
          <Link href="#">
            <Button
              title={"Athena"}
              model="dall-e-2"
              img={<Image src="/athena.png" width={66} height={66} />}
              desc="Athena was the goddess of wisdom, courage, the arts, crafts, and skill in ancient Greek mythology. She help you in creating images based on text input."
            />
          </Link>
          <Link href="/models/hermes">
            <Button
              title={"Hermes"}
              model="lang-god-002"
              img={<Image src="/hermes.png" width={66} height={66} />}
              desc="Hermes was the ancient Greek god of trade, wealth, luck, fertility, animal husbandry, sleep, language, thieves, and travel. He can translate any English text into any specified language that he knows of."
            />
          </Link>
          <Link href="#">
            <Button
              title={"Ares"}
              model="text-evil-002"
              img={<Image src="/ares.png" width={66} height={66} />}
              desc="Ares was the ancient Greek god of war or, more properly, the spirit of battle. He is usually angry and sacractic but if you want to ask him then go ahead."
            />
          </Link>
        </div>
      </main>
    </>
  );
}
